import { classifyText, heuristicScores } from "../pipeline/classify";
import { detectTechnology } from "../pipeline/technologies";
import { truncate } from "../pipeline/normalize";
import { DEFAULT_METRICS, label } from "../constants";
import type {
  LLMProvider, ChatMessage, ChatResult, ItemInput, ClassifyResult, AnalyzeResult, ExperimentDraft,
} from "./types";

function sentences(text: string, n: number): string {
  const parts = text.replace(/\s+/g, " ").match(/[^.!?]+[.!?]+/g) ?? [text];
  return truncate(parts.slice(0, n).join(" ").trim(), 600);
}

/** Offline, deterministic provider. Keeps the system usable with no API key and makes tests reproducible. */
export class HeuristicProvider implements LLMProvider {
  readonly name = "heuristic";

  async chat(messages: ChatMessage[]): Promise<ChatResult> {
    const last = messages[messages.length - 1]?.content ?? "";
    return { text: sentences(last, 3), inputTokens: 0, outputTokens: 0, model: "heuristic" };
  }

  async classify(item: ItemInput): Promise<ClassifyResult> {
    const categories = classifyText(item.title, item.content);
    const s = heuristicScores({ ...item, categories });
    return { categories, ...s, technology: detectTechnology(item.title, item.content)?.name ?? null };
  }

  async analyze(item: ItemInput): Promise<AnalyzeResult> {
    const c = await this.classify(item);
    const tech = detectTechnology(item.title, item.content);
    const summary = item.content ? sentences(item.content, 2) : item.title;
    const areas = c.categories.filter((x) => x !== "OTHER").map(label).join(", ").toLowerCase();
    return {
      ...c,
      summary,
      whyItMatters: areas
        ? `Touches ${areas}${tech ? ` (${tech.name})` : ""}; review whether it changes how you build software with AI.`
        : "Low direct relevance to AI-assisted software engineering.",
      technologyInfo: tech ? { name: tech.name, vendor: tech.vendor, category: tech.category } : null,
      experimentIdea: c.experimentValue >= 60 ? `Compare your current workflow against "${item.title}" on one real task.` : null,
      workflowImprovement: null,
      hype: false,
    };
  }

  async summarize(item: ItemInput): Promise<string> {
    const c = await this.classify(item);
    const body = item.content ? truncate(item.content, 1500) : "Unknown from source";
    return [
      `> Generated by the offline heuristic provider. Configure an LLM provider for a full study note.`,
      `## What is it?\n${item.summary || sentences(item.content || item.title, 2)}`,
      `## Why does it matter?\nCategories: ${c.categories.map(label).join(", ")}. Impact ${c.impact}/100, relevance ${c.relevance}/100.`,
      `## How does it work?\nUnknown from source — read the original: ${item.url ?? ""}`,
      `## What's new?\n${body}`,
      `## What changed?\nUnknown from source`,
      `## Advantages\n- _to fill_`,
      `## Limitations\n- _to fill_`,
      `## Use cases\n- _to fill_`,
      `## Risks\n- _to fill_`,
      `## Example\n_to fill_`,
      `## How we can use it\n_to fill_`,
      `## Should we test it?\n${c.experimentValue >= 60 ? "MAYBE — experiment value is high." : "NO — low experiment value."}`,
    ].join("\n\n");
  }

  async draftExperiment(item: ItemInput): Promise<ExperimentDraft> {
    const tech = detectTechnology(item.title, item.content)?.name ?? item.title;
    return {
      title: `Evaluate: ${truncate(item.title, 100)}`,
      technology: tech,
      problem: "Our current AI-assisted workflow may be slower, costlier or lower quality than it could be.",
      hypothesis: `Using ${tech} improves completion time or quality on a representative task without increasing cost by more than 20%.`,
      baseline: "Current workflow (same task, same model, same repository).",
      newApproach: `Apply ${tech} as described in the source: ${item.url ?? ""}`,
      setup: "Pick one representative task from a real repository. Fix the model and time-box to 60 minutes per variant.",
      steps: "1. Run the task with the baseline workflow and record metrics.\n2. Reset the repository.\n3. Run the task with the new approach and record metrics.\n4. Compare results and decide.",
      metrics: DEFAULT_METRICS,
    };
  }
}
