import Link from "next/link";
import { getDigest, listDigests } from "@/lib/services/digest";
import { PageHeader, Empty } from "@/components/ui";
import { Markdown } from "@/components/markdown";
import { SubmitButton } from "@/components/submit-button";
import { digestNowAction } from "../actions";

export default async function DigestPage({ searchParams }: { searchParams: Promise<{ date?: string }> }) {
  const date = (await searchParams).date;
  const safeDate = date && /^\d{4}-\d{2}-\d{2}$/.test(date) ? date : undefined;
  const [digest, all] = await Promise.all([getDigest(safeDate), listDigests()]);
  return (
    <div>
      <PageHeader title="Daily Digest" subtitle={digest ? `Generated by ${digest.generatedBy}` : undefined}>
        {digest && <a href={`/api/digest/export?date=${digest.digestDate}`} className="btn">Export .md</a>}
        <form action={digestNowAction}><input type="hidden" name="back" value="/digest" /><SubmitButton className="btn-primary" pendingText="Generating…">Generate today&apos;s digest</SubmitButton></form>
      </PageHeader>
      <div className="grid gap-6 lg:grid-cols-4">
        <div className="lg:col-span-3">{digest ? <div className="card"><Markdown>{digest.contentMd}</Markdown></div> : <Empty>No digest yet. Generate one after fetching and analyzing.</Empty>}</div>
        <aside>
          <p className="h2">History</p>
          <ul className="space-y-1 text-sm">
            {all.map((d) => <li key={d.id}><Link href={`/digest?date=${d.digestDate}`} className={d.digestDate === digest?.digestDate ? "font-bold" : "link"}>{d.digestDate}</Link></li>)}
          </ul>
        </aside>
      </div>
    </div>
  );
}
