import { execFile } from "node:child_process";
import { promisify } from "node:util";
import fs from "node:fs/promises";
import path from "node:path";
import { asc, desc, eq } from "drizzle-orm";
import { db, schema } from "../db";
import { slugify } from "../pipeline/technologies";
import { knowledgeToMarkdown } from "./knowledge";
import { experimentToMarkdown, getExperiment } from "./experiments";
import { RADAR_RINGS } from "../constants";

const exec = promisify(execFile);

/** Directories this exporter owns inside the export repo (rewritten on every export). */
const MANAGED = ["knowledge", "experiments", "playbook", "prompts", "digests"] as const;
const MANAGED_FILES = ["README.md", "radar.md"] as const;

export function gitExportConfig() {
  return {
    dir: process.env.GIT_EXPORT_DIR ?? "",
    push: process.env.GIT_EXPORT_PUSH === "true",
    authorName: process.env.GIT_AUTHOR_NAME || "DAILY AI",
    authorEmail: process.env.GIT_AUTHOR_EMAIL || "daily-ai@localhost",
  };
}

async function git(dir: string, args: string[]) {
  const { stdout } = await exec("git", ["-C", dir, ...args], { timeout: 120_000, maxBuffer: 10 * 1024 * 1024 });
  return stdout.trim();
}

/** Write every exportable entity as Markdown under `dir`. Returns the relative paths written. */
export async function writeExport(dir: string): Promise<string[]> {
  // turbopackIgnore: runtime paths only, so the standalone build does not trace the whole project.
  const root = path.resolve(/* turbopackIgnore: true */ dir);
  for (const d of MANAGED) await fs.rm(path.join(/* turbopackIgnore: true */ root, d), { recursive: true, force: true });
  const written: string[] = [];
  const write = async (rel: string, content: string) => {
    const full = path.join(/* turbopackIgnore: true */ root, rel);
    if (!full.startsWith(root + path.sep)) throw new Error(`Refusing to write outside export dir: ${rel}`);
    await fs.mkdir(path.dirname(full), { recursive: true });
    await fs.writeFile(full, content.endsWith("\n") ? content : `${content}\n`, "utf8");
    written.push(rel);
  };

  const [knowledge, experiments, playbooks, prompts, digests, radar] = await Promise.all([
    db.select().from(schema.knowledgeItems).orderBy(asc(schema.knowledgeItems.id)),
    db.select({ id: schema.experiments.id }).from(schema.experiments).orderBy(asc(schema.experiments.id)),
    db.select().from(schema.playbookVersions).orderBy(desc(schema.playbookVersions.createdAt)),
    db.select({ key: schema.prompts.key, description: schema.prompts.description, version: schema.promptVersions.version, template: schema.promptVersions.template, isActive: schema.promptVersions.isActive })
      .from(schema.promptVersions).innerJoin(schema.prompts, eq(schema.prompts.id, schema.promptVersions.promptId)),
    db.select().from(schema.dailyDigests).orderBy(desc(schema.dailyDigests.digestDate)),
    db.select().from(schema.radarItems).orderBy(asc(schema.radarItems.name)),
  ]);

  for (const k of knowledge) await write(`knowledge/${slugify(k.area)}/${k.id}-${slugify(k.title)}.md`, knowledgeToMarkdown(k));
  for (const { id } of experiments) {
    const e = await getExperiment(id);
    if (e) await write(`experiments/${e.code}.md`, experimentToMarkdown(e));
  }
  if (playbooks[0]) await write("playbook/AI-ENGINEERING-PLAYBOOK.md", playbooks[0].contentMd);
  for (const p of playbooks) await write(`playbook/versions/v${p.version}.md`, `<!-- ${p.changelog} -->\n\n${p.contentMd}`);
  for (const p of prompts) {
    await write(`prompts/${p.key}-v${p.version}.md`, `# ${p.key} v${p.version}${p.isActive ? " (active)" : ""}\n\n${p.description}\n\n\`\`\`text\n${p.template}\n\`\`\``);
  }
  for (const d of digests) await write(`digests/${d.digestDate}.md`, d.contentMd);

  await write("radar.md", [
    "# Technology Radar", "",
    ...RADAR_RINGS.flatMap((ring) => {
      const items = radar.filter((r) => r.ring === ring);
      return items.length ? [`## ${ring}`, "", ...items.map((r) => `- **${r.name}** (${r.quadrant})${r.rationale ? ` — ${r.rationale}` : ""}`), ""] : [];
    }),
  ].join("\n"));

  await write("README.md", [
    "# DAILY AI knowledge export", "",
    "Generated by DAILY AI. Files in the managed folders are rewritten on every export, so edit them in DAILY AI, not here.", "",
    `- [AI Engineering Playbook](playbook/AI-ENGINEERING-PLAYBOOK.md) (v${playbooks[0]?.version ?? "—"})`,
    `- [Technology Radar](radar.md)`,
    `- Knowledge: ${knowledge.length} items in \`knowledge/\``,
    `- Experiments: ${experiments.length} in \`experiments/\``,
    `- Prompt versions: ${prompts.length} in \`prompts/\``,
    `- Daily digests: ${digests.length} in \`digests/\``,
  ].join("\n"));
  return written;
}

/** Export to a git working copy, commit if anything changed, and optionally push. */
export async function exportToGit() {
  const cfg = gitExportConfig();
  if (!cfg.dir) return { skipped: "GIT_EXPORT_DIR not set" as const };
  const dir = path.resolve(/* turbopackIgnore: true */ cfg.dir);
  await fs.mkdir(dir, { recursive: true });
  const isRepo = await git(dir, ["rev-parse", "--is-inside-work-tree"]).then((o) => o === "true").catch(() => false);
  if (!isRepo) await git(dir, ["init", "-q"]);

  const files = await writeExport(dir);
  await git(dir, ["add", "-A", "--", ...MANAGED, ...MANAGED_FILES]);
  const staged = await git(dir, ["diff", "--cached", "--name-only"]);
  if (!staged) return { files: files.length, committed: false, pushed: false };

  const changed = staged.split("\n").length;
  await git(dir, [
    "-c", `user.name=${cfg.authorName}`, "-c", `user.email=${cfg.authorEmail}`,
    "commit", "-q", "-m", `DAILY AI export ${new Date().toISOString().slice(0, 10)}: ${changed} file(s) changed`,
  ]);
  const sha = await git(dir, ["rev-parse", "--short", "HEAD"]);
  let pushed = false;
  if (cfg.push) {
    // Credentials come from the repo's own remote / credential helper; never logged here.
    await git(dir, ["push", "-q", "origin", "HEAD"]);
    pushed = true;
  }
  return { files: files.length, committed: true, changed, commit: sha, pushed };
}
