import { and, desc, eq, ilike, or, sql, type SQL } from "drizzle-orm";
import { db, schema } from "../db";
import { ftsMatch } from "./fts";
import { getAI, withFallback } from "../llm";
import { CATEGORY_TO_AREA, type Category } from "../constants";

export async function getArticle(id: number) {
  const [row] = await db
    .select({ article: schema.articles, source: schema.sources })
    .from(schema.articles)
    .leftJoin(schema.sources, eq(schema.articles.sourceId, schema.sources.id))
    .where(eq(schema.articles.id, id));
  return row ?? null;
}

export async function knowledgeForArticle(articleId: number) {
  const [k] = await db.select().from(schema.knowledgeItems).where(eq(schema.knowledgeItems.articleId, articleId)).limit(1);
  return k ?? null;
}

/** LEARN: generate a structured study note for an article and store it as a knowledge item (status LEARNING). */
export async function learnArticle(articleId: number) {
  const existing = await knowledgeForArticle(articleId);
  if (existing) return existing;
  const row = await getArticle(articleId);
  if (!row) throw new Error("Article not found");
  const a = row.article;
  const ai = await getAI();
  const { value: md, by } = await withFallback(
    "learn",
    (p) => p.summarize(
      { title: a.title, content: a.content ?? a.excerpt ?? "", url: a.url, source: row.source?.name, summary: a.summary },
      { ...ai.strong, task: "learn", maxTokens: Math.max(ai.strong.maxTokens, 2000) },
    ),
    ai,
  );
  const cats = ((a.analysis as { categories?: Category[] } | null)?.categories ?? ["OTHER"]) as Category[];
  const content = `${md}\n\n---\nSource: [${a.title}](${a.url})${by !== "heuristic" ? ` · generated by ${by}` : ""}`;
  const [k] = await db.insert(schema.knowledgeItems).values({
    title: a.title,
    area: CATEGORY_TO_AREA[cats[0]] ?? "Models",
    status: "LEARNING",
    summary: a.summary ?? a.excerpt,
    contentMd: content,
    tags: cats.filter((c) => c !== "OTHER"),
    articleId: a.id,
    technologyId: a.technologyId,
  }).returning();
  await db.update(schema.articles).set({ userAction: "learn" }).where(eq(schema.articles.id, a.id));
  return k;
}

export interface KnowledgeInput {
  title: string;
  area: string;
  status: string;
  summary?: string | null;
  contentMd: string;
  tags?: string[];
}

export async function createKnowledge(input: KnowledgeInput) {
  const [k] = await db.insert(schema.knowledgeItems).values({ ...input, tags: input.tags ?? [] }).returning();
  return k;
}

export async function updateKnowledge(id: number, patch: Partial<KnowledgeInput>) {
  await db.update(schema.knowledgeItems).set({ ...patch, updatedAt: new Date() }).where(eq(schema.knowledgeItems.id, id));
}

export async function deleteKnowledge(id: number) {
  await db.delete(schema.knowledgeItems).where(eq(schema.knowledgeItems.id, id));
}

export async function getKnowledge(id: number) {
  const [k] = await db.select().from(schema.knowledgeItems).where(eq(schema.knowledgeItems.id, id));
  return k ?? null;
}

export async function listKnowledge(f: { q?: string; area?: string; status?: string; tag?: string } = {}) {
  const conds: SQL[] = [];
  if (f.area) conds.push(eq(schema.knowledgeItems.area, f.area));
  if (f.status) conds.push(eq(schema.knowledgeItems.status, f.status));
  if (f.tag) conds.push(sql`${f.tag} = any(${schema.knowledgeItems.tags})`);
  if (f.q) {
    conds.push(or(ftsMatch("knowledge_items", f.q), ilike(schema.knowledgeItems.title, `%${f.q}%`))!);
  }
  return db.select().from(schema.knowledgeItems).where(conds.length ? and(...conds) : undefined)
    .orderBy(desc(schema.knowledgeItems.updatedAt)).limit(200);
}

export function knowledgeToMarkdown(k: typeof schema.knowledgeItems.$inferSelect): string {
  return [
    "---",
    `title: ${JSON.stringify(k.title)}`,
    `area: ${k.area}`,
    `status: ${k.status}`,
    `tags: [${k.tags.join(", ")}]`,
    `updated: ${k.updatedAt.toISOString().slice(0, 10)}`,
    "---",
    "",
    `# ${k.title}`,
    "",
    k.summary ? `> ${k.summary.replace(/\n/g, " ")}\n` : "",
    k.contentMd,
    "",
  ].join("\n");
}
